CREATE PROCEDURE `InsertarDocumentosTrabajo` (
	in varIdTDD_Detalle int,
	in varIdNotificador int,
	in varContratoID varchar(255),
	in varCodBarra varchar(255),
	in varNroDocumento varchar(45),
	in varNombreCliente varchar(255),
	in varDireccion varchar(255),
	in varTipo varchar(255),
	in varSE varchar(45),
	in varZona varchar(45),
	in varSector varchar(10),
	in varLibro varchar(10),
	in varFechaEmisionDoc date,
	in varFechaTrabajo date,
	in varFechaAsignacion date,
	in varFechaEjecucion date,
	in varFechaLimiteCargo date,
	in varFechaEntregaASeal date,
	in varEstado varchar(255),
	in varObservaciones varchar(255)
)
BEGIN
	insert into DocumentosTrabajo(
		IdTDD_Detalle,
		IdNotificador,
		ContratoID,
		CodBarra,
		NroDocumento,
		NombreCliente,
		Direccion,
		Tipo,
		SE,
		Zona,
		Sector,
		Libro,
		FechaEmisionDoc,
		FechaTrabajo,
		FechaAsignacion,
		FechaEjecucion,
		FechaLimiteCargo,
		FechaEntregaASeal,
		Estado,
		Observaciones
	)values(
		varIdTDD_Detalle,
		varIdNotificador,
		varContratoID,
		varCodBarra,
		varNroDocumento,
		varNombreCliente,
		varDireccion,
		varTipo,
		varSE,
		varZona,
		varSector,
		varLibro,
		varFechaEmisionDoc,
		varFechaTrabajo,
		varFechaAsignacion,
		varFechaEjecucion,
		varFechaLimiteCargo,
		varFechaEntregaASeal,
		varEstado,
		varObservaciones
	);
END